// Code generated by protoc-gen-go. DO NOT EDIT.
// source: items.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopifyId            int64                `protobuf:"varint,2,opt,name=shopifyId,proto3" json:"shopifyId,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Images               []*Item_Image     `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Vendor               string               `protobuf:"bytes,6,opt,name=vendor,proto3" json:"vendor,omitempty"`
	ItemType          string               `protobuf:"bytes,7,opt,name=itemType,proto3" json:"itemType,omitempty"`
	Collections          []*Collection        `protobuf:"bytes,8,rep,name=collections,proto3" json:"collections,omitempty"`
	Tags                 string               `protobuf:"bytes,9,opt,name=tags,proto3" json:"tags,omitempty"`
	Variants             []*Item_Variant   `protobuf:"bytes,10,rep,name=variants,proto3" json:"variants,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,11,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetShopifyId() int64 {
	if m != nil {
		return m.ShopifyId
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetImages() []*Item_Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Item) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Item) GetItemType() string {
	if m != nil {
		return m.ItemType
	}
	return ""
}

func (m *Item) GetCollections() []*Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

func (m *Item) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Item) GetVariants() []*Item_Variant {
	if m != nil {
		return m.Variants
	}
	return nil
}

func (m *Item) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Item) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type Item_Image struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopifyId            int64                `protobuf:"varint,2,opt,name=shopifyId,proto3" json:"shopifyId,omitempty"`
	Src                  string               `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Alt                  string               `protobuf:"bytes,4,opt,name=alt,proto3" json:"alt,omitempty"`
	Position             string               `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Item_Image) Reset()         { *m = Item_Image{} }
func (m *Item_Image) String() string { return proto.CompactTextString(m) }
func (*Item_Image) ProtoMessage()    {}
func (*Item_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0, 0}
}

func (m *Item_Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item_Image.Unmarshal(m, b)
}
func (m *Item_Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item_Image.Marshal(b, m, deterministic)
}
func (m *Item_Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item_Image.Merge(m, src)
}
func (m *Item_Image) XXX_Size() int {
	return xxx_messageInfo_Item_Image.Size(m)
}
func (m *Item_Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Item_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Item_Image proto.InternalMessageInfo

func (m *Item_Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item_Image) GetShopifyId() int64 {
	if m != nil {
		return m.ShopifyId
	}
	return 0
}

func (m *Item_Image) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *Item_Image) GetAlt() string {
	if m != nil {
		return m.Alt
	}
	return ""
}

func (m *Item_Image) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Item_Image) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Item_Image) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type Item_Variant struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopifyId            int64                `protobuf:"varint,2,opt,name=shopifyId,proto3" json:"shopifyId,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Sku                  string               `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Position             string               `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	RegularPrice         string               `protobuf:"bytes,6,opt,name=regularPrice,proto3" json:"regularPrice,omitempty"`
	SalesPrice           string               `protobuf:"bytes,7,opt,name=salesPrice,proto3" json:"salesPrice,omitempty"`
	InventoryQuantity    string               `protobuf:"bytes,8,opt,name=inventoryQuantity,proto3" json:"inventoryQuantity,omitempty"`
	Weight               string               `protobuf:"bytes,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,11,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Item_Variant) Reset()         { *m = Item_Variant{} }
func (m *Item_Variant) String() string { return proto.CompactTextString(m) }
func (*Item_Variant) ProtoMessage()    {}
func (*Item_Variant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{0, 1}
}

func (m *Item_Variant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item_Variant.Unmarshal(m, b)
}
func (m *Item_Variant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item_Variant.Marshal(b, m, deterministic)
}
func (m *Item_Variant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item_Variant.Merge(m, src)
}
func (m *Item_Variant) XXX_Size() int {
	return xxx_messageInfo_Item_Variant.Size(m)
}
func (m *Item_Variant) XXX_DiscardUnknown() {
	xxx_messageInfo_Item_Variant.DiscardUnknown(m)
}

var xxx_messageInfo_Item_Variant proto.InternalMessageInfo

func (m *Item_Variant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item_Variant) GetShopifyId() int64 {
	if m != nil {
		return m.ShopifyId
	}
	return 0
}

func (m *Item_Variant) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item_Variant) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Item_Variant) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

func (m *Item_Variant) GetRegularPrice() string {
	if m != nil {
		return m.RegularPrice
	}
	return ""
}

func (m *Item_Variant) GetSalesPrice() string {
	if m != nil {
		return m.SalesPrice
	}
	return ""
}

func (m *Item_Variant) GetInventoryQuantity() string {
	if m != nil {
		return m.InventoryQuantity
	}
	return ""
}

func (m *Item_Variant) GetWeight() string {
	if m != nil {
		return m.Weight
	}
	return ""
}

func (m *Item_Variant) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Item_Variant) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type Collection struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopifyId            string               `protobuf:"bytes,2,opt,name=shopifyId,proto3" json:"shopifyId,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Image                string               `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{1}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collection) GetShopifyId() string {
	if m != nil {
		return m.ShopifyId
	}
	return ""
}

func (m *Collection) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Collection) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Collection) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Collection) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Collection) GetUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item              *Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{4}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item              *Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{5}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item              *Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{6}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{7}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type DeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Deleted              int64    `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type ListRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{10}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ListResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data                 []*Item `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c6e54f42122eb82, []int{11}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListResponse) GetData() []*Item {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "v1.Item")
	proto.RegisterType((*Item_Image)(nil), "v1.Item.Image")
	proto.RegisterType((*Item_Variant)(nil), "v1.Item.Variant")
	proto.RegisterType((*Collection)(nil), "v1.Collection")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "v1.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "v1.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "v1.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "v1.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "v1.DeleteResponse")
	proto.RegisterType((*ListRequest)(nil), "v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "v1.ListResponse")
}

func init() { proto.RegisterFile("items.proto", fileDescriptor_8c6e54f42122eb82) }

var fileDescriptor_8c6e54f42122eb82 = []byte{
	// 916 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xc6, 0xde, 0x5d, 0xef, 0xe6, 0x78, 0xb3, 0x6c, 0xa6, 0x15, 0x38, 0x56, 0xd5, 0x58, 0x96,
	0x90, 0xc2, 0xaa, 0xb5, 0xb3, 0x4b, 0xae, 0x42, 0x85, 0x54, 0x12, 0x89, 0x14, 0x71, 0x51, 0x4c,
	0xe1, 0x82, 0xbb, 0xa9, 0x3d, 0x75, 0x86, 0x3a, 0x1e, 0xe3, 0x19, 0x6f, 0x88, 0x50, 0x85, 0xd4,
	0x17, 0x40, 0x82, 0x3b, 0x9e, 0x80, 0xf7, 0xe1, 0x09, 0x90, 0x78, 0x01, 0x24, 0x1e, 0x00, 0x79,
	0x66, 0xbc, 0xb1, 0x1b, 0x36, 0x0d, 0x25, 0xe2, 0x6a, 0x67, 0xce, 0x7c, 0xe7, 0x3b, 0x7f, 0xdf,
	0xcc, 0x1a, 0x26, 0x45, 0xc9, 0x92, 0x2a, 0x16, 0x3c, 0x28, 0x4a, 0x26, 0x18, 0x32, 0x97, 0x73,
	0x77, 0x27, 0x65, 0x2c, 0xcd, 0x48, 0x28, 0x2d, 0x4f, 0xab, 0x67, 0xa1, 0xa0, 0xa7, 0x84, 0x0b,
	0x7c, 0x5a, 0x28, 0x90, 0x7b, 0x47, 0x03, 0x70, 0x41, 0x43, 0x9c, 0xe7, 0x4c, 0x60, 0x41, 0x59,
	0xae, 0x29, 0xdc, 0x7b, 0xf2, 0x27, 0xbe, 0x9f, 0x92, 0xfc, 0x3e, 0x3f, 0xc3, 0x69, 0x4a, 0xca,
	0x90, 0x15, 0x12, 0x71, 0x19, 0xed, 0xff, 0x38, 0x82, 0xe1, 0x63, 0x95, 0x03, 0x9a, 0x80, 0x49,
	0x13, 0xc7, 0xf0, 0x8c, 0xdd, 0x8d, 0xc8, 0xa4, 0x09, 0xba, 0x03, 0x1b, 0xfc, 0x84, 0x15, 0xf4,
	0xd9, 0xf9, 0xa3, 0xc4, 0x31, 0x3d, 0x63, 0xb7, 0x17, 0x5d, 0x18, 0xd0, 0x6d, 0x18, 0x08, 0x2a,
	0x32, 0xe2, 0xf4, 0xa4, 0x83, 0xda, 0x20, 0x0f, 0xec, 0x84, 0xf0, 0xb8, 0xa4, 0x32, 0xa2, 0xd3,
	0x97, 0x67, 0x6d, 0x13, 0x7a, 0x1f, 0x2c, 0x7a, 0x8a, 0x53, 0xc2, 0x9d, 0x81, 0xd7, 0xdb, 0xb5,
	0x17, 0x5b, 0xc1, 0x72, 0x1e, 0xe8, 0x14, 0x82, 0x47, 0xf5, 0x49, 0xa4, 0x01, 0xe8, 0x1d, 0xb0,
	0x96, 0x24, 0x4f, 0x58, 0xe9, 0x58, 0x92, 0x47, 0xef, 0xea, 0x20, 0xba, 0x6f, 0x4f, 0xce, 0x0b,
	0xe2, 0x0c, 0x55, 0x90, 0x96, 0x09, 0xed, 0x81, 0x1d, 0xb3, 0x2c, 0x23, 0xb1, 0xac, 0xd5, 0x19,
	0xc9, 0x48, 0x93, 0x3a, 0xd2, 0xe1, 0xca, 0x1c, 0xb5, 0x21, 0x08, 0x41, 0x5f, 0xe0, 0x94, 0x3b,
	0x1b, 0x92, 0x4c, 0xae, 0x51, 0x08, 0xa3, 0x25, 0x2e, 0x29, 0xce, 0x05, 0x77, 0x40, 0x52, 0xdc,
	0x6a, 0x27, 0xfb, 0x95, 0x3a, 0x8b, 0x56, 0x20, 0xb4, 0x0f, 0xc3, 0xb8, 0x24, 0x58, 0x90, 0xc4,
	0xb1, 0x3d, 0x63, 0xd7, 0x5e, 0xb8, 0x81, 0x9a, 0x55, 0xd0, 0x0c, 0x33, 0x78, 0xd2, 0x0c, 0x33,
	0x6a, 0xa0, 0xb5, 0x57, 0x55, 0x24, 0xd2, 0x6b, 0xfc, 0x7a, 0x2f, 0x0d, 0x75, 0x7f, 0x37, 0x60,
	0x20, 0xdb, 0xf5, 0x2f, 0xe7, 0x36, 0x85, 0x1e, 0x2f, 0x63, 0x3d, 0xb5, 0x7a, 0x59, 0x5b, 0x70,
	0x26, 0xf4, 0xac, 0xea, 0x25, 0x72, 0x61, 0x54, 0x30, 0x4e, 0xe5, 0x08, 0x07, 0xd2, 0xbc, 0xda,
	0xb7, 0x6b, 0xb4, 0xde, 0xa8, 0xc6, 0xe1, 0xf5, 0x6b, 0xfc, 0xd3, 0x84, 0xa1, 0xee, 0xf2, 0x8d,
	0xa8, 0xb3, 0xae, 0xfd, 0x79, 0xd5, 0x54, 0xca, 0x9f, 0x57, 0x57, 0x56, 0xea, 0xc3, 0xb8, 0x24,
	0x69, 0x95, 0xe1, 0xf2, 0x71, 0x49, 0x63, 0xa2, 0x45, 0xd8, 0xb1, 0xa1, 0xbb, 0x00, 0x1c, 0x67,
	0x84, 0x2b, 0x84, 0x52, 0x62, 0xcb, 0x82, 0xee, 0xc1, 0x16, 0xcd, 0x97, 0x24, 0x17, 0xac, 0x3c,
	0xff, 0xbc, 0xc2, 0xb9, 0xa0, 0xe2, 0xdc, 0x19, 0x49, 0xd8, 0xe5, 0x83, 0x5a, 0xf0, 0x67, 0x84,
	0xa6, 0x27, 0x42, 0xcb, 0x50, 0xef, 0xda, 0x3d, 0x87, 0x37, 0xea, 0xb9, 0x7d, 0xed, 0x9e, 0xfb,
	0x7f, 0x19, 0x00, 0x17, 0x97, 0xe4, 0xf5, 0x6d, 0xdf, 0xb8, 0x89, 0x47, 0xe1, 0x36, 0x0c, 0xe4,
	0x9d, 0xd7, 0x33, 0x50, 0x9b, 0xff, 0x53, 0x6a, 0xfe, 0x31, 0x6c, 0x1e, 0x4a, 0x82, 0x88, 0x7c,
	0x5b, 0x11, 0x2e, 0xe4, 0xad, 0x28, 0xa8, 0xae, 0xbc, 0x5e, 0xa2, 0xf7, 0x60, 0xa8, 0xdf, 0x18,
	0x59, 0xb8, 0xbd, 0xb0, 0x5b, 0xaf, 0x41, 0xd4, 0x9c, 0xf9, 0x0b, 0x98, 0x34, 0x4c, 0xbc, 0x60,
	0x39, 0x27, 0xff, 0x40, 0xa5, 0xba, 0x6a, 0x36, 0x5d, 0xf5, 0x43, 0xb0, 0x23, 0x82, 0x93, 0xf5,
	0xb1, 0x5f, 0x75, 0xf8, 0x04, 0xc6, 0xca, 0x61, 0x6d, 0x88, 0x6b, 0x66, 0x7b, 0x0c, 0x9b, 0x5f,
	0xca, 0x16, 0xfc, 0xe7, 0xba, 0x1f, 0xc0, 0xa4, 0x61, 0x5a, 0x9b, 0x94, 0x73, 0x31, 0x1b, 0x75,
	0x65, 0x57, 0xfd, 0x9f, 0xc3, 0xe6, 0x11, 0xc9, 0xc8, 0x55, 0x79, 0xbc, 0xda, 0x83, 0x07, 0x30,
	0x69, 0x5c, 0xae, 0x0a, 0x98, 0x48, 0xcc, 0x2a, 0xa0, 0xde, 0xfa, 0x3b, 0x60, 0x7f, 0x46, 0xb9,
	0x58, 0x1b, 0xce, 0x7f, 0x08, 0x63, 0x05, 0x58, 0x4b, 0xbe, 0x03, 0xfd, 0x04, 0x0b, 0xec, 0x98,
	0xf2, 0xbf, 0xa1, 0xd3, 0x15, 0x79, 0xb0, 0xf8, 0xb5, 0x07, 0x13, 0x6d, 0xf9, 0x82, 0x94, 0xcb,
	0xfa, 0x41, 0x38, 0x84, 0x7e, 0xcd, 0x8a, 0xde, 0xae, 0xd1, 0xad, 0x04, 0xdc, 0xe9, 0x85, 0x41,
	0x05, 0xf4, 0x9d, 0x97, 0xbf, 0xfd, 0xf1, 0xb3, 0x89, 0xd0, 0x34, 0x5c, 0xce, 0xc3, 0xe6, 0x43,
	0x21, 0xc4, 0x59, 0x86, 0x8e, 0xc1, 0x52, 0x12, 0x43, 0xf2, 0xdf, 0xb3, 0x23, 0x5c, 0x17, 0xb5,
	0x4d, 0x9a, 0xea, 0x5d, 0x49, 0xb5, 0xe5, 0x8f, 0xdb, 0x54, 0x07, 0xc6, 0x0c, 0x1d, 0x41, 0xbf,
	0xd6, 0x91, 0x4a, 0xa7, 0x25, 0x41, 0x95, 0x4e, 0x5b, 0x62, 0xfe, 0xb6, 0xe4, 0xb8, 0x85, 0xb6,
	0x3a, 0xe9, 0x7c, 0x4f, 0x93, 0x17, 0xa8, 0x02, 0x4b, 0x8d, 0x5e, 0xe5, 0xd3, 0x11, 0x94, 0xca,
	0xa7, 0xab, 0x0c, 0xff, 0x48, 0x72, 0x7d, 0xe4, 0x6e, 0x77, 0xb9, 0xf4, 0x2a, 0xa0, 0xc9, 0x8b,
	0x03, 0x63, 0xf6, 0xf5, 0xdd, 0xc5, 0x95, 0xe7, 0xe8, 0x53, 0xb0, 0x94, 0x00, 0x54, 0xd8, 0x8e,
	0x7e, 0x54, 0xd8, 0xae, 0x3e, 0x9a, 0x12, 0x66, 0x97, 0x4b, 0xf8, 0xf8, 0xa5, 0xf1, 0xd3, 0xc3,
	0x1f, 0xd0, 0x36, 0x4c, 0xf5, 0xbc, 0xb8, 0xa7, 0x27, 0xe6, 0xbf, 0xb5, 0xe8, 0xcd, 0x83, 0xbd,
	0x99, 0x61, 0x2c, 0xa6, 0xb8, 0x28, 0x32, 0x1a, 0xcb, 0x0f, 0xa8, 0xf0, 0x1b, 0xce, 0xf2, 0x83,
	0x4b, 0x96, 0xe8, 0x43, 0xe8, 0xed, 0xef, 0xed, 0xa3, 0x7d, 0x98, 0x45, 0x44, 0x54, 0x65, 0x4e,
	0x12, 0xef, 0xec, 0x84, 0xe4, 0x9e, 0x38, 0x21, 0x5e, 0x49, 0x38, 0xab, 0xca, 0x98, 0x78, 0x09,
	0x23, 0xdc, 0xcb, 0x99, 0xf0, 0xc8, 0x77, 0x94, 0x8b, 0x00, 0x59, 0xd0, 0xff, 0xc5, 0x34, 0x86,
	0x4f, 0x2d, 0xf9, 0x42, 0x7d, 0xf0, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0x62, 0x42, 0x32,
	0x17, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/v1.ItemService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ItemService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ItemService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ItemService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ItemService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ItemService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ItemService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "items.proto",
}
